#!/bin/bash

# Import colors
. ~/.dotfiles/colors
. ~/.dotfiles/git
. ~/.dotfiles/git-completion

# PS
if [ $USER = "root" ]; then
	PS1=${BOLD}${YELLOW}"\t "${BOLD}${RED}"\u "${BOLD}${GREEN}"\w "${RED}"\$(parse_git_branch)\$(parse_git_status)"${BOLD}${BLUE}"\\$ "${DEFAULT}
else
	PS1=${BOLD}${YELLOW}"\t "${BOLD}${BLUE}"\u "${BOLD}${GREEN}"\w "${RED}"\$(parse_git_branch)\$(parse_git_status)"${BOLD}${BLUE}"\\$ "${DEFAULT}
fi
alias ls='ls --color=auto'
alias ll="ls -h"

# export go
export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
export GO111MODULE=on

# alias bashrc
alias bashrc="vim ~/.bashrc && source ~/.bashrc"

# docker
alias fig="docker-compose"

# git config alias
gitconfig() {
	git config user.name "$GIT_NAME"
	git config user.email "$GIT_EMAIL"
}

utc() {
	date -d @$1
}      

alias lint="golangci-lint run"

repackage() {
	for file in $(find $1 -type f -name "*.go"); do
		package=${file%/*}
		package="${package##*/}"
		sed -i "s/^package .*$/package $package/g" $file
	done;	
}
