#!/bin/bash

# Import colors
. ~/.dotfiles/colors
. ~/.dotfiles/git
. ~/.dotfiles/git-completion

# PS
if [ $USER = "root" ]; then
	PS1=${BOLD}${YELLOW}"\t "${BOLD}${RED}"\u "${BOLD}${GREEN}"\w "${RED}"\$(parse_git_branch)\$(parse_git_status)"${BOLD}${BLUE}"\\$ "${DEFAULT}
else
	PS1=${BOLD}${YELLOW}"\t "${BOLD}${BLUE}"\u "${BOLD}${GREEN}"\w "${RED}"\$(parse_git_branch)\$(parse_git_status)"${BOLD}${BLUE}"\\$ "${DEFAULT}
fi
alias ls='ls --color=auto'
alias ll="ls -h"

# export go
export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin:$HOME/.bin
export GO111MODULE=on

# alias bashrc
alias bashrc="vim ~/.bashrc && source ~/.bashrc"

# docker
alias fig="docker-compose"

# env loading
dotenv() {
	dir=$1
	if [ $dir = "." ]; then dir=`pwd`; fi
	while true; do
		if [ $dir = "/" ]; then break
		else
			export $(cat $dir/.env 2> /dev/null | xargs ) > /dev/null
			dir=$(dirname $dir)
		fi
	done
}


# git config alias
gitconfig() {
	git config user.name "$GIT_NAME"
	git config user.email "$GIT_EMAIL"
}

utc() {
	date -d @$1
}

run() {
	make build-$1 && fig up --build $1
}

move() {
	for from in $(find -type f -name "*$1*"); do
		to=$(echo "$from" | sed -e 's/'$1'/'$2'/g');
		mv $from $to;
		echo "move $from to $to"
	done;
}

# docker-compose exec -T api_mysql mysql -u root --password=rootpass database < ~/Work/dumps/2019-10-15_preprod.sql
# select EVENT_OBJECT_TABLE, TRIGGER_NAME, action_timing, EVENT_MANIPULATION from information_schema.triggers;
