#!/bin/bash

# Import colors
. ~/.dotfiles/colors
. ~/.dotfiles/git
. ~/.dotfiles/git-completion
. ~/.dotfiles/go
. ~/.dotfiles/to

# PS
if [ $USER = "root" ]; then
	PS1=${BOLD}${YELLOW}"\t "${BOLD}${RED}"\u "${BOLD}${GREEN}"\w "${RED}"\$(parse_git_branch)\$(parse_git_status)"${BOLD}${BLUE}"\\$ "${DEFAULT}
else
	PS1=${BOLD}${YELLOW}"\t "${BOLD}${BLUE}"\u "${BOLD}${GREEN}"\w "${RED}"\$(parse_git_branch)\$(parse_git_status)"${BOLD}${BLUE}"\\$ "${DEFAULT}
fi
alias ls='ls --color=auto'
alias ll="ls -h"

# alias bashrc
alias bashrc="vim ~/.bashrc && source ~/.bashrc"
