#!#/bin/bash

# shortcut to specific directories
to() {
	case $1 in

		# SoCloz go
		"github")     cd "$GOPATH/src/github.com"; ;;
		"pocs")       cd "$GOPATH/src/github.com/SoCloz/pocs"; ;;
		"api")        cd "$GOPATH/src/github.com/SoCloz/go/api"; ;;
		"feeder")     cd "$GOPATH/src/github.com/SoCloz/go/feeder"; ;;
		"tools")      cd "$GOPATH/src/github.com/SoCloz/go/tools"; ;;

		# SoCloz misc
		"platform")   cd "/home/socloz/dev/platform"; ;;

		# Perso
		"adeptus")    cd "$GOPATH/src/github.com/elwinar/adeptus"; ;;
		"pool")       cd "$GOPATH/src/github.com/moxar/pool"; ;;	
		"dotfiles")   cd && cd ".dotfiles"; ;;

		# SSH
		"prod")       ssh alexandre@admin.socloz2.typhon.net; ;;
		"docker")     ssh socloz@localhost; ;;
		"rdd")	      ncmpc -h elwinar.com; ;;

		# help
		"help")       cat ~/.dotfiles/to; ;;

		# Error
		*)            echo  "${RED}error: ${DEFAULT}undefined target \"$1\""; ;;
	esac
}
